# References:
# - https://github.com/jdhealy/PrettyColors/blob/development/.travis.yml
env:
  global:
    - LC_CTYPE=en_US.UTF-8
os: osx
language: c
matrix:
  exclude:
    # Note: Workaround travis-ci/travis-ci#4681
    # Exclude default job which lacks our included environment variables.
    - os: osx
  include:
    - osx_image: xcode8
      env:
        - XCODE_SDK=iphonesimulator
          XCODE_ACTION="build-for-testing test-without-building"
          XCODE_SCHEME=RZBluetooth
          XCODE_DESTINATION="name=iPhone 6s"
    - osx_image: xcode7.3
      env:
        - XCODE_SDK=iphonesimulator
          XCODE_ACTION="build-for-testing test-without-building"
          XCODE_SCHEME=RZBluetooth
          XCODE_DESTINATION="name=iPhone 6s"
    - osx_image: xcode7.3
      env:
        - XCODE_SDK=iphonesimulator
          XCODE_ACTION="build-for-testing test-without-building"
          XCODE_SCHEME=RZBluetooth
          XCODE_DESTINATION="name=iPhone 4s"
git:
  submodules: false
before_install:
  - git submodule update --init --recursive
script:
  - xcodebuild ${XCODE_ACTION}
      -project RZBluetooth.xcodeproj
      -scheme ${XCODE_SCHEME}
      -sdk ${XCODE_SDK}
      -destination "${XCODE_DESTINATION}"
      CODE_SIGNING_REQUIRED=NO
      CODE_SIGN_IDENTITY=
notifications:
  email: false
