# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.3
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- export PYTHONUSERBASE=~/.local
script:
- build.sh

